### ISSUE TITLE
Fails to install on Windows 10

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP-PowerShellEditorServices#5]
PowerShellEditorServices.zip is downloaded and extracted to _PowerShellEditorServices_ directory in _Package Storage_.

But then LSP complains about installation failure and prints following lines to console.

```
Unable to start subprocess for PowerShellEditorServices
Traceback (most recent call last):
  File "C:\Apps\Sublime Text\Data\Packages\LSP\plugin\core\windows.py", line 310, in start_async
    plugin_class.install_or_update()
  File "C:\Apps\Sublime Text\Data\Packages\LSP-PowerShellEditorServices\plugin.py", line 149, in install_or_update
    os.rename(os.path.join(cls.storage_path(), cls.name()), cls.basedir())
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Apps\\Sublime Text\\Data\\Package Storage\\LSP-PowerShellEditorServices'
```

**Comment by rwols** [comment]
New version with the fix will appear on PC soon.
